hostname="freebsd"
keymap="pl.kbd"
ifconfig_vtnet0="DHCP"
ifconfig_vtnet0_ipv6="inet6 accept_rtadv"
sshd_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
zfs_enable="YES"
dbus_enable="YES"
sddm_enable="YES"
kld_list="virtio_gpu"

polkitd_enable="YES"
hald_enable="YES"
# Mouse dla virtual-manager
moused_nondefault_enable="NO"
